#!/bin/sh

echo -e "\n[local] start script here: waiting for DB to be ready..." && sleep 3

echo "Using DJANGO_SETTINGS_MODULE=$DJANGO_SETTINGS_MODULE"

while true; do
    set -x
    psql -h "$DB_HOST" -U "$DB_USERNAME" -c "CREATE DATABASE $DB_NAME"
    python3 necktie/manage.py migrate
    python3 necktie/manage.py loaddata districts languages specializations doctors openinghours
    python3 necktie/manage.py runserver 0.0.0.0:8000
    echo -e "\n(!) Server exited with RC=$?. Restarting after some wait..."
    set +x
    sleep 3  # wait before retrying
done
