# Generated by Django 3.2.15 on 2022-08-08 04:22

from decimal import Decimal
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="District",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Doctor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100)),
                (
                    "price",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=10,
                        validators=[
                            django.core.validators.MinValueValidator(Decimal("0.01"))
                        ],
                    ),
                ),
                ("is_price_inclusive", models.BooleanField(default=False)),
                ("address", models.TextField()),
                (
                    "district",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to="doctors.district",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Language",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="Specialization",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=100, unique=True)),
            ],
        ),
        migrations.CreateModel(
            name="OpeningHour",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "weekday",
                    models.CharField(
                        choices=[
                            ("Sunday", "Sunday"),
                            ("Monday", "Monday"),
                            ("Tuesday", "Tuesday"),
                            ("Wednesday", "Wednesday"),
                            ("Thursday", "Thursday"),
                            ("Friday", "Friday"),
                            ("Saturday", "Saturday"),
                            ("Public Holiday", "Public Holiday"),
                        ],
                        max_length=14,
                    ),
                ),
                ("start_hour", models.TimeField(blank=True, null=True)),
                ("end_hour", models.TimeField(blank=True, null=True)),
                ("is_closed", models.BooleanField(default=False)),
                (
                    "doctor",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="opening_hours",
                        to="doctors.doctor",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="doctor",
            name="language",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="doctors.language"
            ),
        ),
        migrations.AddField(
            model_name="doctor",
            name="specialization",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT, to="doctors.specialization"
            ),
        ),
        migrations.AddConstraint(
            model_name="openinghour",
            constraint=models.UniqueConstraint(
                condition=models.Q(
                    ("start_hour__isnull", False), ("end_hour__isnull", False)
                ),
                fields=("doctor", "weekday", "start_hour", "end_hour"),
                name="unique_doctor_opening_hour",
            ),
        ),
        migrations.AddConstraint(
            model_name="openinghour",
            constraint=models.UniqueConstraint(
                condition=models.Q(("is_closed", True)),
                fields=("doctor", "weekday", "is_closed"),
                name="unique_doctor_closed_hour",
            ),
        ),
    ]
